services:
  api:
    container_name: rob-api
    image: ${DOCKERHUB_USERNAME}/rob-api:latest
    restart: always
    environment:
      - PORT=${PORT} # Puerto para la API
      - DATABASE_URL=${MONGODB_URI} # URL de conexión a MongoDB que la app espera
      - JWT_SECRET=${JWT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: rob-mongo
    restart: always
    volumes:
      - ./data:/data/db

  nginx:
    image: nginx:1.25-alpine
    container_name: rob-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    # Usamos una imagen de Nginx que tiene Certbot instalado
    # y ejecutamos nuestro script de entrada.
    command: /bin/sh -c "apk add --no-cache certbot openssl && chmod +x /entrypoint.sh && /entrypoint.sh"