services:
  api:
    container_name: rob-api
    # Indica a Docker Compose que construya la imagen desde el directorio actual
    # usando el Dockerfile que se encuentra ahí.
    build: .
    image: eduartrob/rob-api:latest # Nombre que se le dará a la imagen construida localmente
    restart: always
    # Las variables de entorno se cargarán desde el archivo .env
    env_file:
      - .env

  nginx:
    image: nginx:1.25-alpine
    container_name: rob-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    # Usamos una imagen de Nginx que tiene Certbot instalado
    # y ejecutamos nuestro script de entrada (que ya instala Certbot).
    command: /entrypoint.sh